# Sustainable Development Goal №16

In this notebook, we will read, save, clean, and merge data for the Sustainable Development Goal №16.

Let's start by importing relevant libraries and checking their versions.

In [360]:
# Importing libraries
import pandas as pd
import matplotlib.pyplot as plt

In [361]:
# Printing verions of Python modules and packages with watermark - the IPython magic extension.
%load_ext watermark

%watermark -v -p numpy,pandas,matplotlib

The watermark extension is already loaded. To reload it, use:
  %reload_ext watermark
Python implementation: CPython
Python version       : 3.9.7
IPython version      : 7.29.0

numpy     : 1.20.3
pandas    : 1.3.4
matplotlib: 3.4.3

## Target 16.b

*Definition: Promote and enforce non-discriminatory laws and policies for sustainable development.*

### Indicator 16.b.1

*Definition: Proportion of population reporting having personally felt discriminated against or harassed in the previous 12 months on the basis of a ground of discrimination prohibited under international human rights law*

For this Indicator, we will use the NYPD Hate Crimes dataset containing confirmed hate crime incidents in NYC. Hate Crimes are offenses that are motivated in whole or substantial part by a person's, a group's or a place's identification with a particular race, religion, ethnicity, gender, age, disability, ancestry, national origin or sexual orientation.

We are going to build a variable that reflects the UN's definition for Indicator 16.b.1 provided above. 

In this variable, we will look at the number of hate crime complaints filed with NYPD by year and several geographies. Therefore, the definition for the `hate_crimes` variable that we will create is going to be as follows: *Number of complaints filed by people reporting having personally felt discriminated against or harassed in the previous 12 months on the basis of race, religion, ethnicity, gender, age, disability, ancestry, national origin or sexual orientation.*

This dataset is partially available (2019-2021) on the [NYC Open Data Portal](https://data.cityofnewyork.us/Public-Safety/NYPD-Hate-Crimes/bqiq-cu78) and is updated every month. Previous data (2017-2018) is available on the [Official Website of the City of New York](https://www1.nyc.gov/site/nypd/stats/reports-analysis/hate-crimes.page). In this Index, we only use data for 2019 and earlier years, as most of our indicators are based on Census estimates which are only partially available for 2020 (only general tables included, microdata is not available), and the Census Bureau reported that there are some data quality concerns for the ACS survey due to low response rate during Covid-19 pandemic. Therefore, we will drop all values for 2020 and after available in our datasets.

#### 1. Reading in data as a pandas dataframe

In [362]:
# reading in data as a url from NYC Open Data
host = 'https://data.cityofnewyork.us/resource/bqiq-cu78.csv'

# saving data as a pandas dataframe named 'building_footprints_csv'
hate_crimes = pd.read_csv(host)

#### 2. Data Inspection

                                                    Data Dictionary
---------------------------------------------
| Column Name | Description | 
| ------------ | ------------- | 
| Full Complaint ID | Year in which incident occurred | 
| Month Number | Month in which incident occurred | 
| Record Create Date | Date report was filed | 
| Complaint Precinct Code | NYPD Precinct in which incident occurred | 
| Patrol Borough Name | NYPD Patrol Borough in which incident occurred |
| County | County in which incident occurred  | 
| Law Code Category Description | Category of offense |
| Offense Description | A description of the offense | 
| PD Code Description | The NYPD description of the offense |
| Bias Motive Description | Bias Motive Description |
| Offense Category | General categorization of hate crime type |
| Arrest Date | Date arrest was made (if arrest happened) |
| Arrest Id | Identifier for arrest (if made) |

In [363]:
# previewing the first five rows 
hate_crimes.head()

,full_complaint_id,complaint_year_number,month_number,record_create_date,complaint_precinct_code,patrol_borough_name,county,law_code_category_description,offense_description,pd_code_description,bias_motive_description,offense_category,arrest_date,arrest_id
0,201904612204817,2019,2,2019-02-08T00:00:00.000,46,PATROL BORO BRONX,BRONX,FELONY,FELONY ASSAULT,"ASSAULT 2,1,UNCLASSIFIED",ANTI-MALE HOMOSEXUAL (GAY),Sexual Orientation,2019-02-08T00:00:00.000,B31678218
1,201904812229517,2019,3,2019-03-09T00:00:00.000,48,PATROL BORO BRONX,BRONX,MISDEMEANOR,ASSAULT 3 & RELATED OFFENSES,ASSAULT 3,ANTI-WHITE,Race/Color,2019-03-09T00:00:00.000,B31682790
2,201904812226617,2019,3,2019-03-08T00:00:00.000,48,PATROL BORO BRONX,BRONX,MISDEMEANOR,ASSAULT 3 & RELATED OFFENSES,ASSAULT 3,ANTI-WHITE,Race/Color,2019-03-09T00:00:00.000,B31682806
3,201904812231317,2019,3,2019-03-10T00:00:00.000,48,PATROL BORO BRONX,BRONX,MISDEMEANOR,ASSAULT 3 & RELATED OFFENSES,ASSAULT 3,ANTI-WHITE,Race/Color,2019-03-09T00:00:00.000,B31682806
4,201904212405517,2019,5,2019-05-11T00:00:00.000,42,PATROL BORO BRONX,BRONX,FELONY,ROBBERY,"ROBBERY,POCKETBOOK/CARRIED BAG",ANTI-MUSLIM,Religion/Religious Practice,2019-05-10T00:00:00.000,B31692174

In [364]:
# previewing the last five rows of our dataframe
hate_crimes.tail()

,full_complaint_id,complaint_year_number,month_number,record_create_date,complaint_precinct_code,patrol_borough_name,county,law_code_category_description,offense_description,pd_code_description,bias_motive_description,offense_category,arrest_date,arrest_id
995,202102412173717,2021,3,2021-03-25T00:00:00.000,24,PATROL BORO MAN NORTH,NEW YORK,MISDEMEANOR,CRIMINAL MISCHIEF & RELATED OF,"CRIMINAL MISCHIEF 4TH, GRAFFIT",ANTI-JEWISH,Religion/Religious Practice,NaN,NaN
996,202102412180417,2021,3,2021-03-30T00:00:00.000,24,PATROL BORO MAN NORTH,NEW YORK,FELONY,MISCELLANEOUS PENAL LAW,AGGRAVATED HARASSMENT 1,ANTI-JEWISH,Religion/Religious Practice,NaN,NaN
997,202102412192317,2021,4,2021-04-07T00:00:00.000,24,PATROL BORO MAN NORTH,NEW YORK,MISDEMEANOR,ASSAULT 3 & RELATED OFFENSES,ASSAULT 3,ANTI-ASIAN,Race/Color,NaN,NaN
998,202102412251317,2021,5,2021-05-16T00:00:00.000,24,PATROL BORO MAN NORTH,NEW YORK,MISDEMEANOR,ASSAULT 3 & RELATED OFFENSES,ASSAULT 3,ANTI-MALE HOMOSEXUAL (GAY),Sexual Orientation,NaN,NaN
999,202102412327917,2021,7,2021-07-11T00:00:00.000,24,PATROL BORO MAN NORTH,NEW YORK,MISDEMEANOR,ASSAULT 3 & RELATED OFFENSES,ASSAULT 3,ANTI-MALE HOMOSEXUAL (GAY),Sexual Orientation,NaN,NaN

In [365]:
# printing the shape or dimensions of our dataframe (i.e. rows, columns)
hate_crimes.shape

(1000, 14)

In [366]:
# the object's type
type(hate_Crimes)

pandas.core.frame.DataFrame

In [367]:
# printing the data types of our columns
hate_crimes.dtypes

full_complaint_id                 int64
complaint_year_number             int64
month_number                      int64
record_create_date               object
complaint_precinct_code           int64
patrol_borough_name              object
county                           object
law_code_category_description    object
offense_description              object
pd_code_description              object
bias_motive_description          object
offense_category                 object
arrest_date                      object
arrest_id                        object
dtype: object

In [368]:
# printing the column names, non-null counts, and data types of our columns
hate_crimes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 14 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   full_complaint_id              1000 non-null   int64
 1   complaint_year_number          1000 non-null   int64
 2   month_number                   1000 non-null   int64
 3   record_create_date             1000 non-null   object
 4   complaint_precinct_code        1000 non-null   int64
 5   patrol_borough_name            1000 non-null   object
 6   county                         1000 non-null   object
 7   law_code_category_description  1000 non-null   object
 8   offense_description            1000 non-null   object
 9   pd_code_description            1000 non-null   object
 10  bias_motive_description        1000 non-null   object
 11  offense_category               1000 non-null   object
 12  arrest_date                    397 non-null    object
 13  arrest_id                      397 non-null    object
dtypes: int64(4), object(10)
memory usage: 109.5+ KB

In [369]:
# printing descriptive statistics 
hate_crimes.describe()

,full_complaint_id,complaint_year_number,month_number,complaint_precinct_code
count,1.000000e+03,1000.000000,1000.000000,1000.000000
mean,2.019878e+14,2019.822000,6.100000,56.266000
std,8.205222e+10,0.827648,3.279139,38.145673
min,2.019001e+14,2019.000000,1.000000,1.000000
25%,2.019071e+14,2019.000000,3.000000,18.000000
50%,2.020019e+14,2020.000000,6.000000,61.000000
75%,2.021005e+14,2021.000000,9.000000,90.000000
max,2.021123e+14,2021.000000,12.000000,123.000000

In [370]:
hate_crimes.describe(include=['O'])

,record_create_date,patrol_borough_name,county,law_code_category_description,offense_description,pd_code_description,bias_motive_description,offense_category,arrest_date,arrest_id
count,1000,1000,1000,1000,1000,1000,1000,1000,397,397
unique,563,8,5,4,17,48,23,8,237,396
top,2021-04-25T00:00:00.000,PATROL BORO MAN SOUTH,NEW YORK,MISDEMEANOR,CRIMINAL MISCHIEF & RELATED OF,AGGRAVATED HARASSMENT 1,ANTI-JEWISH,Religion/Religious Practice,2021-05-01T00:00:00.000,B31682806
freq,9,261,393,513,266,235,461,514,14,2

In [371]:
# printing the number of null/na values in each column
hate_crimes.isna().sum()

full_complaint_id                  0
complaint_year_number              0
month_number                       0
record_create_date                 0
complaint_precinct_code            0
patrol_borough_name                0
county                             0
law_code_category_description      0
offense_description                0
pd_code_description                0
bias_motive_description            0
offense_category                   0
arrest_date                      603
arrest_id                        603
dtype: int64

#### 3. Cleaning and aggregating data

We next limit our data to only relevant columns and collapse it by precinct and year to construct the desired variable.

As we only need the number of complaints per year by precinct, we can subset our dataset only to leave the columns representing the year, complaint id, and the precinct number.

In [372]:
# subsetting our data to only include relevant columns
hate_crimes = hate_crimes[['full_complaint_id', 'complaint_year_number', 'complaint_precinct_code']]

In [373]:
# keeping if the year is 2019
hate_crimes = hate_crimes[hate_crimes['complaint_year_number'] == 2019]
print(hate_crimes)

     full_complaint_id  complaint_year_number  complaint_precinct_code
0      201904612204817                   2019                       46
1      201904812229517                   2019                       48
2      201904812226617                   2019                       48
3      201904812231317                   2019                       48
4      201904212405517                   2019                       42
..                 ...                    ...                      ...
713    201912112660417                   2019                      121
714    201912212334717                   2019                      122
715    201912212498017                   2019                      122
716    201912212568117                   2019                      122
717    201912312372817                   2019                      123

[447 rows x 3 columns]

In [378]:
# collapsing data by precinct
hate_crimes_2019 = hate_crimes.groupby(['complaint_precinct_code']).nunique()
hate_crimes_2019 = hate_crimes_2019.reset_index()
# renaming the columns
hate_crimes_2019 = hate_crimes_2019.rename(columns={"full_complaint_id": "hate_crimes", "complaint_year_number": "year", "complaint_precinct_code": "precinct"})
hate_crimes_2019

    precinct  hate_crimes  year
0          1           12     1
1          5            6     1
2          6            6     1
3          7            7     1
4          9            4     1
..       ...          ...   ...
68       115            9     1
69       120            2     1
70       121            4     1
71       122            3     1
72       123            1     1

[73 rows x 3 columns]

In [382]:
# correcting the year value
hate_crimes_2019['year'] = 2019
hate_crimes_2019

    precinct  hate_crimes  year
0          1           12  2019
1          5            6  2019
2          6            6  2019
3          7            7  2019
4          9            4  2019
..       ...          ...   ...
68       115            9  2019
69       120            2  2019
70       121            4  2019
71       122            3  2019
72       123            1  2019

[73 rows x 3 columns]

In [384]:
hate_crimes_2019.describe()

         precinct  hate_crimes    year
count   73.000000    73.000000    73.0
mean    63.232877     5.780822  2019.0
std     36.429353     4.444868     0.0
min      1.000000     1.000000  2019.0
25%     32.000000     3.000000  2019.0
50%     66.000000     5.000000  2019.0
75%    100.000000     7.000000  2019.0
max    123.000000    20.000000  2019.0

In [383]:
hate_crimes_2019.isna().sum()

precinct       0
hate_crimes    0
year           0
dtype: int64

sum stats. Clean , read and merge with 2017 2018, collapse,